# Generated by Django 5.2.1 on 2025-05-21 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_salle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='salles/'),
        ),
        migrations.AddField(
            model_name='salle',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app2.categoriesalle'),
        ),
    ]
