# Generated by Django 5.2.1 on 2025-05-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_categoriesalle_salle_image_salle_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementexterne',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipements_externes', to='app2.reservation'),
        ),
    ]
